name = Irlanda Connection
description = Layout for Irlanda Connection awesome Website - includes top image
template = irlanda-connection

zone_enabled = true

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[header_image] = Header Image
regions[sidebar_first] = First Sidebar
regions[content] = Content
regions[footer] = Footer

; ========================================
; Zones
; ========================================
zones[header_image] = Header Image
