name = Irlanda Connection
description = Layout for Irlanda Connection awesome Website
template = irlanda-connection

zone_enabled = true

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted]    = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Zones
; ========================================
zones[header_image] = Header Image