source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  
end
