name = Home
description = The homepage Layout
template = home-layout

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/irlanda-connection.styles.css

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted]    = Highlighted
regions[wrapper-first] = Wrapper First
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Zones
; ========================================
zones[header_image] = Header Image