name = Home
description = The homepage Layout
template = home-layout

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/home.layout.css

; ========================================
; Regions
; ========================================
regions[header] = Header
regions[navigation] = Navigation
regions[content] = Content
regions[footer] = Footer