name = Home
description = The homepage Layout
template = home-layout

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/irlanda-connection.styles.css

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[help] = Help
regions[content] = Content
regions[wrapper-first] = Wrapper First
regions[wrapper-second] = Wrapper Second
regions[wrapper-third] = Wrapper Third
regions[sidebar_first] = First Sidebar
regions[footer] = Footer
